const state = { source: null, graph: null, positions: {}, selected: null, templates: {} };
const canvas = document.querySelector("#canvas"), edges = document.querySelector("#edges");
const empty = document.querySelector("#empty-state"), form = document.querySelector("#node-form");

async function request(path, payload) {
  const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
  const data = await response.json(); if (!response.ok) throw new Error(data.error || "Request failed."); return data;
}
function uniqueId(base) { const ids = new Set((state.source.nodes || []).map(n => n.id)); let id = base, number = 1; while (ids.has(id)) id = `${base}_${number++}`; return id; }
function selectedNode() { return (state.source.nodes || []).find(node => node.id === state.selected); }
function positionFor(id, index) { return state.positions[id] || { x: 35 + (index % 4) * 250, y: 35 + Math.floor(index / 4) * 150 }; }
function render() {
  canvas.innerHTML = ""; edges.innerHTML = '<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#6680ae"/></marker></defs>';
  if (!state.source) { empty.hidden = false; return; } empty.hidden = true;
  (state.graph.nodes || []).forEach((node, index) => {
    const pos = positionFor(node.id, index); state.positions[node.id] = pos;
    const element = document.createElement("article"); element.className = `node ${node.terminal ? "terminal" : ""} ${state.selected === node.id ? "selected" : ""}`;
    element.style.left = `${pos.x}px`; element.style.top = `${pos.y}px`; element.dataset.id = node.id;
    element.innerHTML = `<div class="node-id">${node.id}</div><div class="node-label"></div><div class="node-type">${node.answer_type}</div>`;
    element.querySelector(".node-label").textContent = node.label; element.addEventListener("click", () => selectNode(node.id)); makeDraggable(element); canvas.append(element);
  });
  requestAnimationFrame(drawEdges); renderInspector();
}
function drawEdges() { state.graph.edges.forEach(edge => { const a = state.positions[edge.source], b = state.positions[edge.target]; if (!a || !b) return; const line = document.createElementNS("http://www.w3.org/2000/svg", "line"); line.setAttribute("x1", a.x + 205); line.setAttribute("y1", a.y + 43); line.setAttribute("x2", b.x); line.setAttribute("y2", b.y + 43); edges.append(line); }); }
function makeDraggable(element) { let start; element.addEventListener("pointerdown", event => { if (event.button !== 0) return; const current = state.positions[element.dataset.id]; start = { pointerX: event.clientX, pointerY: event.clientY, nodeX: current.x, nodeY: current.y }; element.setPointerCapture(event.pointerId); }); element.addEventListener("pointermove", event => { if (!start) return; state.positions[element.dataset.id] = { x: Math.max(0, start.nodeX + event.clientX - start.pointerX), y: Math.max(0, start.nodeY + event.clientY - start.pointerY) }; element.style.left = `${state.positions[element.dataset.id].x}px`; element.style.top = `${state.positions[element.dataset.id].y}px`; edges.innerHTML = '<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#6680ae"/></marker></defs>'; drawEdges(); }); element.addEventListener("pointerup", () => { start = null; }); }
function selectNode(id) { state.selected = id; render(); }
function renderInspector() { const node = selectedNode(); document.querySelector("#selection-help").hidden = Boolean(node); form.hidden = !node; if (!node) return; document.querySelector("#node-id").value = node.id; document.querySelector("#node-question").value = node.question || ""; document.querySelector("#node-answer-type").value = node.answer_type || ""; document.querySelector("#node-incoming").value = (node.allowed_from || []).join("\n"); document.querySelector("#node-terminal").checked = node.terminal === true; }
function refresh(source) { state.source = source; state.positions = {}; state.selected = null; return request("/api/parse", { source }).then(data => { state.source = data.source; state.graph = data.graph; render(); }); }
function displayValidation(validation) { const container = document.querySelector("#validation"); const issues = validation.issues || []; container.innerHTML = validation.status === "passed" ? '<p class="ok">Validation passed.</p>' : ""; issues.slice(0, 30).forEach(issue => { const el = document.createElement("div"); el.className = `issue ${issue.severity || ""}`; el.textContent = `${issue.validator}: ${issue.code} — ${issue.message}`; container.append(el); }); if (issues.length > 30) container.insertAdjacentHTML("beforeend", `<p class="hint">${issues.length - 30} additional findings are available through the CLI report.</p>`); }
document.querySelector("#file-input").addEventListener("change", async event => { const file = event.target.files[0]; if (!file) return; try { const data = await request("/api/parse", { yaml: await file.text() }); state.source = data.source; state.graph = data.graph; state.positions = {}; render(); } catch (error) { alert(error.message); } });
document.querySelector("#validate").addEventListener("click", async () => { if (!state.source) return; try { const data = await request("/api/validate", { source: state.source }); displayValidation(data.validation); } catch (error) { alert(error.message); } });
document.querySelector("#download").addEventListener("click", async () => { if (!state.source) return; const data = await request("/api/export", { source: state.source }); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([data.yaml], { type: "application/x-yaml" })); link.download = "program.edited.ordo.yaml"; link.click(); URL.revokeObjectURL(link.href); });
document.querySelectorAll("[data-template]").forEach(button => button.addEventListener("click", async () => { if (!state.source) return alert("Open a YAML file first."); const template = structuredClone(state.templates[button.dataset.template]); template.id = uniqueId(template.id); if (!Array.isArray(state.source.nodes)) state.source.nodes = []; state.source.nodes.push(template); await refresh(state.source); selectNode(template.id); }));
document.querySelector("#add-transition").addEventListener("click", async () => { if (!state.source) return; const sourceId = prompt("Source node ID:", state.selected || ""); const targetId = prompt("Target node ID:"); if (!sourceId || !targetId) return; const source = state.source.nodes.find(n => n.id === sourceId), target = state.source.nodes.find(n => n.id === targetId); if (!source || !target) return alert("Both node IDs must exist."); source.on_answer ||= {}; source.on_answer[`to_${targetId}`] = { next: targetId }; target.allowed_from ||= []; if (!target.allowed_from.includes(sourceId)) target.allowed_from.push(sourceId); await refresh(state.source); });
form.addEventListener("submit", async event => { event.preventDefault(); const node = selectedNode(), oldId = node.id, id = document.querySelector("#node-id").value.trim(); if (!id) return; node.id = id; node.question = document.querySelector("#node-question").value; node.answer_type = document.querySelector("#node-answer-type").value; node.allowed_from = document.querySelector("#node-incoming").value.split("\n").map(x => x.trim()).filter(Boolean); node.terminal = document.querySelector("#node-terminal").checked; if (oldId !== id) { state.source.nodes.forEach(n => { if (Array.isArray(n.allowed_from)) n.allowed_from = n.allowed_from.map(x => x === oldId ? id : x); }); } await refresh(state.source); selectNode(id); });
document.querySelector("#delete-node").addEventListener("click", async () => { if (!state.selected || !confirm(`Delete ${state.selected}?`)) return; state.source.nodes = state.source.nodes.filter(n => n.id !== state.selected); await refresh(state.source); });
Promise.all([fetch("/api/node-templates").then(r => r.json()), fetch("/api/tree-modules").then(r => r.json())]).then(([templates, modules]) => { state.templates = templates.templates; document.querySelector("#module-list").innerHTML = (modules.library.templates || []).map(item => `<p><strong>${item.id}</strong><br><span class="hint">${item.purpose}</span></p>`).join(""); });
