from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import json

from .loader import load_package


def _read_json(path: str | Path) -> dict[str, Any]:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"release diff report not found: {p}")
    return json.loads(p.read_text(encoding="utf-8"))


def _section_summary(name: str, section: dict[str, Any]) -> str:
    s = section.get("summary") or {}
    added = s.get("added", 0)
    removed = s.get("removed", 0)
    changed = s.get("changed", 0)
    unchanged = s.get("unchanged", 0)
    if not (added or removed or changed):
        return f"- `{name}`: без змін ({unchanged} unchanged)."
    parts = []
    if added:
        parts.append(f"{added} added")
    if removed:
        parts.append(f"{removed} removed")
    if changed:
        parts.append(f"{changed} changed")
    if unchanged:
        parts.append(f"{unchanged} unchanged")
    return f"- `{name}`: " + ", ".join(parts) + "."


def _list_changes(section: dict[str, Any], *, max_items: int = 20) -> list[str]:
    lines: list[str] = []
    for path in section.get("added", [])[:max_items]:
        lines.append(f"  - added: `{path}`")
    for path in section.get("removed", [])[:max_items]:
        lines.append(f"  - removed: `{path}`")
    for item in section.get("changed", [])[:max_items]:
        lines.append(f"  - changed: `{item.get('path')}`")
    total = len(section.get("added", [])) + len(section.get("removed", [])) + len(section.get("changed", []))
    if total > max_items:
        lines.append(f"  - ... ще {total - max_items} змін не показано в короткому звіті")
    return lines


def generate_release_notes(package_path: str | Path, *, diff: str | Path | None = None, out: str | Path | None = None) -> dict[str, Any]:
    """Generate human-readable Markdown release notes from a release diff report.

    This is an M16 derived artifact: it does not invent changes. It summarizes the
    controlled release_diff_report.json generated by M15.
    """
    root, manifest, source, tests = load_package(package_path)
    reports_dir = root / manifest.get("reports", "reports")
    reports_dir.mkdir(parents=True, exist_ok=True)
    diff_path = Path(diff) if diff else reports_dir / "release_diff_report.json"
    diff_report = _read_json(diff_path)

    pkg = diff_report.get("package") or {}
    summary = diff_report.get("summary") or {}
    reproducibility = diff_report.get("reproducibility") or {}
    status = diff_report.get("status", "unknown")
    changed_sections = summary.get("changed_sections") or []

    title = f"Release notes: {pkg.get('name') or manifest.get('name')} {pkg.get('version') or manifest.get('version')}"
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"Generated at: `{datetime.now(timezone.utc).isoformat()}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    if status == "identical":
        lines.append("This release is reproducible against the selected base provenance. No controlled release sections changed.")
    else:
        lines.append("This release differs from the selected base provenance.")
    lines.append("")
    lines.append(f"- Diff status: `{status}`")
    lines.append(f"- Fully reproducible against base: `{str(reproducibility.get('fully_reproducible_against_base')).lower()}`")
    lines.append(f"- Archive hash equal: `{str(reproducibility.get('archive_hash_equal')).lower()}`")
    lines.append(f"- Changed sections: `{', '.join(changed_sections) if changed_sections else 'none'}`")
    lines.append("")

    scalar_changes = diff_report.get("scalar_changes") or []
    lines.append("## Metadata changes")
    lines.append("")
    if not scalar_changes:
        lines.append("No package/toolchain/release metadata changes were detected.")
    else:
        for item in scalar_changes:
            lines.append(f"- `{item.get('field')}`: `{item.get('base')}` → `{item.get('head')}`")
    lines.append("")

    lines.append("## Section summary")
    lines.append("")
    sections = diff_report.get("sections") or {}
    for name in ["source_files", "lock_files", "compiled_ir", "runtime_trace_and_state", "generated_outputs", "reports"]:
        if name in sections:
            lines.append(_section_summary(name, sections[name]))
    lines.append("")

    lines.append("## Changed artifacts")
    lines.append("")
    any_detail = False
    for name, section in sections.items():
        details = _list_changes(section)
        if details:
            any_detail = True
            lines.append(f"### {name}")
            lines.append("")
            lines.extend(details)
            lines.append("")
    if not any_detail:
        lines.append("No added, removed, or changed controlled artifacts were detected.")
        lines.append("")

    lines.append("## Handoff note")
    lines.append("")
    if status == "identical":
        lines.append("The release can be treated as reproducible against the selected base, assuming the base provenance is trusted.")
    else:
        lines.append("Review the changed sections before handoff. If changes are intended, accept this release and store the new provenance as the next base.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Generated by `ordo generate-release-notes` from `reports/release_diff_report.json`.")
    content = "\n".join(lines) + "\n"

    out_path = Path(out) if out else reports_dir / "release_notes.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")

    report = {
        "schema": "ordo.release_notes.v0.1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": "generated",
        "package": {"name": manifest.get("name"), "version": manifest.get("version")},
        "source_diff_report": str(diff_path),
        "output": str(out_path),
        "summary": {
            "diff_status": status,
            "changed_sections": changed_sections,
            "scalar_changes": len(scalar_changes),
            "fully_reproducible_against_base": reproducibility.get("fully_reproducible_against_base"),
        },
    }
    report_path = reports_dir / "release_notes_report.json"
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report
