from __future__ import annotations

from pathlib import Path
from datetime import datetime, timezone
from typing import Any
import hashlib
import json
import uuid

EXCLUDED_PARTS = {".git", "__pycache__", ".ordo-generated", "cli_embedded", "release"}
EXCLUDED_NAMES = {
    "package_report.json",
    "BUILD_MANIFEST.json",
    "SHA256SUMS.txt",
    # Deterministic packaging-derived artifacts: regenerated by `ordo package`
    # from the validated source tree, so they must not invalidate the identity
    # that binds the release validation report to that tree (M87.7).
    "ordo.runtime.json",
    "targets.manifest.json",
    "program.ordo.view",
    "pre_zip_reconciliation_report.json",
    "runtime_status_report.json",
    # Runtime-mutable by design; integrity is protected by its own
    # tamper-evident hash chain (verify-session), not by the static identity.
    "session.ordo.trace",
}


def _included(path: Path, root: Path) -> bool:
    rel = path.relative_to(root)
    if not path.is_file():
        return False
    if any(part in EXCLUDED_PARTS for part in rel.parts):
        return False
    if path.suffix == ".pyc" or path.name in EXCLUDED_NAMES:
        return False
    if "reports" in rel.parts and path.name in {
        "build_identity.json",
        "release_validation_report.json",
        "ci_release_evidence.json",
    }:
        return False
    return True


def current_tree_sha256(root: str | Path) -> str:
    root = Path(root).resolve()
    h = hashlib.sha256()
    for path in sorted(p for p in root.rglob("*") if _included(p, root)):
        rel = path.relative_to(root).as_posix().encode("utf-8")
        data = path.read_bytes()
        h.update(len(rel).to_bytes(8, "big"))
        h.update(rel)
        h.update(len(data).to_bytes(8, "big"))
        h.update(data)
    return h.hexdigest()


def new_build_identity(root: str | Path, *, build_session_id: str | None = None) -> dict[str, Any]:
    root = Path(root).resolve()
    return {
        "schema_version": "ordo.build_identity.v1",
        "build_session_id": build_session_id or str(uuid.uuid4()),
        "current_tree_sha256": current_tree_sha256(root),
        "created_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
    }


def write_build_identity(root: str | Path, output: str | Path | None = None, *, build_session_id: str | None = None) -> dict[str, Any]:
    root = Path(root).resolve()
    payload = new_build_identity(root, build_session_id=build_session_id)
    target = Path(output) if output else root / "reports" / "build_identity.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return payload


def bind_report(report: dict[str, Any], identity: dict[str, Any]) -> dict[str, Any]:
    report["build_identity"] = {
        "schema_version": identity["schema_version"],
        "build_session_id": identity["build_session_id"],
        "current_tree_sha256": identity["current_tree_sha256"],
    }
    return report


def validate_report_binding(report: dict[str, Any], identity: dict[str, Any]) -> list[dict[str, Any]]:
    actual = report.get("build_identity") or {}
    issues = []
    if actual.get("build_session_id") != identity.get("build_session_id"):
        issues.append({"severity": "error", "code": "ORDO-BUILD-001", "message": "report build session does not match current build session"})
    if actual.get("current_tree_sha256") != identity.get("current_tree_sha256"):
        issues.append({"severity": "error", "code": "ORDO-BUILD-002", "message": "report tree identity does not match current tree"})
    return issues
